// Productos registrados en SAG Chile aprobados para uso en frutales (énfasis en cerezos)
// Fuente: Registro SAG plaguicidas.sag.gob.cl — datos referentes, verificar etiqueta vigente

export type GrupoProducto =
  | 'FUNGICIDA'
  | 'INSECTICIDA'
  | 'ACARICIDA'
  | 'HERBICIDA'
  | 'FERTILIZANTE_FOLIAR'
  | 'BIOESTIMULANTE'
  | 'OTRO'

export type TipoDosis = 'por100L' | 'porHectarea' | 'riego'

export interface ProductoSAG {
  id: string
  nombreComercial: string
  ingredienteActivo: string
  grupo: GrupoProducto
  plaga: string
  dosis: string
  unidad: string
  tipoDosis: TipoDosis
  carencia?: string
  observaciones?: string
}

export const GRUPOS_PRODUCTO: { value: GrupoProducto; label: string; color: string }[] = [
  { value: 'FUNGICIDA',          label: 'Fungicidas',              color: 'bg-purple-100 text-purple-800 border-purple-200' },
  { value: 'INSECTICIDA',        label: 'Insecticidas',            color: 'bg-red-100 text-red-800 border-red-200' },
  { value: 'ACARICIDA',          label: 'Acaricidas',              color: 'bg-orange-100 text-orange-800 border-orange-200' },
  { value: 'HERBICIDA',          label: 'Herbicidas',              color: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
  { value: 'FERTILIZANTE_FOLIAR',label: 'Fertilizantes Foliares',  color: 'bg-green-100 text-green-800 border-green-200' },
  { value: 'BIOESTIMULANTE',     label: 'Bioestimulantes',         color: 'bg-teal-100 text-teal-800 border-teal-200' },
  { value: 'OTRO',               label: 'Otros',                   color: 'bg-gray-100 text-gray-800 border-gray-200' },
]

export const PRODUCTOS_SAG: ProductoSAG[] = [

  // ── FUNGICIDAS ────────────────────────────────────────────────────────────────
  {
    id: 'oxicup-50wg',
    nombreComercial: 'Oxicup 50 WG',
    ingredienteActivo: 'Oxicloruro de Cobre 50%',
    grupo: 'FUNGICIDA',
    plaga: 'Cáncer bacterial (Pseudomonas syringae)',
    dosis: '500',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    observaciones: 'Aplicar preferentemente en caída de hojas y receso invernal. Detener en yema hinchada.',
  },
  {
    id: 'cupro-bordoles',
    nombreComercial: 'Cupro Bordolés 25 WP',
    ingredienteActivo: 'Caldo Bordelés 85,5%',
    grupo: 'FUNGICIDA',
    plaga: 'Cáncer bacterial, hongos de la madera',
    dosis: '750',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '—',
  },
  {
    id: 'agrocopper-sp',
    nombreComercial: 'Agrocopper SP',
    ingredienteActivo: 'Sulfato de Cobre Pentahidratado',
    grupo: 'FUNGICIDA',
    plaga: 'Cáncer bacterial preventivo',
    dosis: '80',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'amistar-top',
    nombreComercial: 'Amistar Top 325 SC',
    ingredienteActivo: 'Azoxystrobin 200 g/L + Difenoconazole 125 g/L',
    grupo: 'FUNGICIDA',
    plaga: 'Monilinia, Botrytis, Oidio',
    dosis: '40',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },
  {
    id: 'bellis',
    nombreComercial: 'Bellis 38 WG',
    ingredienteActivo: 'Boscalid 25,2% + Piraclostrobin 12,8%',
    grupo: 'FUNGICIDA',
    plaga: 'Botrytis, Monilinia, Alternaria',
    dosis: '66',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '0 días',
    observaciones: 'Máximo 2 aplicaciones por temporada.',
  },
  {
    id: 'switch-625wg',
    nombreComercial: 'Switch 62.5 WG',
    ingredienteActivo: 'Cyprodinil 37,5% + Fludioxonil 25%',
    grupo: 'FUNGICIDA',
    plaga: 'Botrytis, Monilinia pre y postcosecha',
    dosis: '80',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },
  {
    id: 'teldor-500sc',
    nombreComercial: 'Teldor 500 SC',
    ingredienteActivo: 'Fenhexamida 500 g/L',
    grupo: 'FUNGICIDA',
    plaga: 'Botrytis cinerea',
    dosis: '80',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '3 días',
    observaciones: 'Rotación con fungicidas de otro grupo.',
  },
  {
    id: 'atlas-43sc',
    nombreComercial: 'Atlas 43 SC (Vertice 43 SC)',
    ingredienteActivo: 'Tebuconazole 430 g/L',
    grupo: 'FUNGICIDA',
    plaga: 'Monilinia, Oidio, Cáncer bacterial',
    dosis: '40',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '14 días',
  },
  {
    id: 'manzate-200',
    nombreComercial: 'Manzate 200 (Mancozeb 80% WP)',
    ingredienteActivo: 'Mancozeb 80%',
    grupo: 'FUNGICIDA',
    plaga: 'Tiro de munición, hongos de la madera, Alternaria',
    dosis: '240',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '45 días',
    observaciones: 'Incompatible con productos alcalinos.',
  },
  {
    id: 'captan-80wdg',
    nombreComercial: 'Captan 80 WDG (Merpan)',
    ingredienteActivo: 'Captan 80%',
    grupo: 'FUNGICIDA',
    plaga: 'Monilinia, Botrytis, Podredumbre marrón',
    dosis: '225',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '1 día',
  },
  {
    id: 'comet-250ec',
    nombreComercial: 'Comet 250 EC',
    ingredienteActivo: 'Piraclostrobin 250 g/L',
    grupo: 'FUNGICIDA',
    plaga: 'Oidio, Monilinia, Botrytis',
    dosis: '20',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },
  {
    id: 'agrygent-plus',
    nombreComercial: 'Agrygent Plus',
    ingredienteActivo: 'Sulfato de Gentamicida + Clorhidrato de Oxitetraciclina',
    grupo: 'FUNGICIDA',
    plaga: 'Cáncer bacterial (curativo)',
    dosis: '80',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    observaciones: 'Usar solo en caso necesario. Antibiótico agrícola registrado SAG.',
  },
  {
    id: 'cercobin-m',
    nombreComercial: 'Cercobin M WP',
    ingredienteActivo: 'Tiofanato Metílico 700 g/kg + Maneb',
    grupo: 'FUNGICIDA',
    plaga: 'Hongos de la madera, Oidio',
    dosis: '100',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },
  {
    id: 'nativo-75wg',
    nombreComercial: 'Nativo 75 WG',
    ingredienteActivo: 'Trifloxystrobin 25% + Tebuconazole 50%',
    grupo: 'FUNGICIDA',
    plaga: 'Oidio, Monilinia, Alternaria',
    dosis: '50',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '14 días',
  },

  // ── INSECTICIDAS ──────────────────────────────────────────────────────────────
  {
    id: 'intrepid-240sc',
    nombreComercial: 'Intrepid 240 SC',
    ingredienteActivo: 'Metoxifenocide 240 g/L',
    grupo: 'INSECTICIDA',
    plaga: 'Polilla del manzano, tortrices, Cydia pomonella',
    dosis: '20',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
    observaciones: 'Selectivo para larvas de lepidópteros. En zona Escama Coma, intercambiar por Acetamiprid.',
  },
  {
    id: 'acetamiprid-20sp',
    nombreComercial: 'Acetamiprid 20% SP (Mospilan)',
    ingredienteActivo: 'Acetamiprid 20%',
    grupo: 'INSECTICIDA',
    plaga: 'Drosophila suzukii, Trips, Polillas, Escama, Pulgones',
    dosis: '50',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '8 días',
  },
  {
    id: 'zero-5ec',
    nombreComercial: 'Zero 5 EC (Karate Zeon)',
    ingredienteActivo: 'Lambda-Cyhalotrina 50 g/L',
    grupo: 'INSECTICIDA',
    plaga: 'Polillas, tortrices, Drosophila suzukii',
    dosis: '15',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '14 días',
  },
  {
    id: 'success-48',
    nombreComercial: 'Success 48 (Entrust)',
    ingredienteActivo: 'Spinosad 480 g/L',
    grupo: 'INSECTICIDA',
    plaga: 'Trips de California, Drosophila suzukii',
    dosis: '12',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
    observaciones: 'Respetar carencia según especie. Máximo 3 aplicaciones por temporada.',
  },
  {
    id: 'turbine',
    nombreComercial: 'Turbine (Flonicamida)',
    ingredienteActivo: 'Flonicamida 50%',
    grupo: 'INSECTICIDA',
    plaga: 'Trips de California',
    dosis: '20',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },
  {
    id: 'avaunt',
    nombreComercial: 'Avaunt 15 SC',
    ingredienteActivo: 'Indoxacarb 150 g/L',
    grupo: 'INSECTICIDA',
    plaga: 'Burrito de los frutales (Naupactus xanthographus)',
    dosis: '17',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '14 días',
    observaciones: 'Aplicar solo con historial o presencia confirmada de burritos.',
  },
  {
    id: 'admiral-10ec',
    nombreComercial: 'Admiral 10 EC',
    ingredienteActivo: 'Piriproxifeno 100 g/L',
    grupo: 'INSECTICIDA',
    plaga: 'Escama San José (Diaspidiotus perniciosus)',
    dosis: '60',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    observaciones: 'Aplicar según movimiento de ninfas. En alta presión usar 70 cc/100L con 2000 L/ha mojamiento.',
  },
  {
    id: 'orthene-75sp',
    nombreComercial: 'Orthene 75 SP',
    ingredienteActivo: 'Acefato 750 g/kg',
    grupo: 'INSECTICIDA',
    plaga: 'Burrito de los frutales (adultos)',
    dosis: '100',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '14 días',
    observaciones: 'En postcosecha. Cada 20 días hasta marzo-abril.',
  },
  {
    id: 'coragen-20sc',
    nombreComercial: 'Coragen 20 SC',
    ingredienteActivo: 'Chlorantraniliprole 200 g/L',
    grupo: 'INSECTICIDA',
    plaga: 'Polillas, tortrices, Cydia pomonella',
    dosis: '15',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '3 días',
    observaciones: 'Alta selectividad. Compatible con fauna benéfica.',
  },
  {
    id: 'imidan-70wp',
    nombreComercial: 'Imidan 70 WP',
    ingredienteActivo: 'Fosfamet (Phosmet) 700 g/kg',
    grupo: 'INSECTICIDA',
    plaga: 'Lepidópteros, Escama, Trips',
    dosis: '150',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },
  {
    id: 'benevia-od10',
    nombreComercial: 'Benevia OD 10',
    ingredienteActivo: 'Cyantraniliprole 100 g/L',
    grupo: 'INSECTICIDA',
    plaga: 'Drosophila suzukii, Trips, Polillas',
    dosis: '150',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },

  // ── ACARICIDAS ────────────────────────────────────────────────────────────────
  {
    id: 'acramite-480sc',
    nombreComercial: 'Acramite 480 SC',
    ingredienteActivo: 'Bifenazato 240 g/L',
    grupo: 'ACARICIDA',
    plaga: 'Arañita bimaculada (Tetranychus urticae), arañita roja',
    dosis: '50',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
    observaciones: 'Máximo 1 aplicación al año. No aplicar en floración.',
  },
  {
    id: 'envidor-240sc',
    nombreComercial: 'Envidor 240 SC',
    ingredienteActivo: 'Spirodiclofen 240 g/L',
    grupo: 'ACARICIDA',
    plaga: 'Arañita roja europea (Panonychus ulmi), arañita bimaculada',
    dosis: '60',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
    observaciones: 'Máximo 1 aplicación por temporada. Control de todos los estados. 5-6 semanas de efecto.',
  },
  {
    id: 'citroliv',
    nombreComercial: 'Citroliv (Winspray)',
    ingredienteActivo: 'Aceite emulsible mineral/vegetal 97%',
    grupo: 'ACARICIDA',
    plaga: 'Huevos de arañita bimaculada y roja',
    dosis: '2000',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    observaciones: 'Aplicar máximo hasta estado ramillete (BBCH 55). No mezclar con azufre.',
  },
  {
    id: 'magister-20sc',
    nombreComercial: 'Magister 20 SC',
    ingredienteActivo: 'Fenazaquin 200 g/L',
    grupo: 'ACARICIDA',
    plaga: 'Arañitas (todos los estados)',
    dosis: '75',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '14 días',
    observaciones: 'Máximo 1 aplicación por temporada. 14-21 días de efecto.',
  },
  {
    id: 'borneo-110sc',
    nombreComercial: 'Borneo 110 SC',
    ingredienteActivo: 'Etoxazol 110 g/L',
    grupo: 'ACARICIDA',
    plaga: 'Arañitas (huevos, larvas, ninfas)',
    dosis: '25',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
    observaciones: 'Sin efecto sobre adultos. Excelente residualidad.',
  },
  {
    id: 'floramite-240sc',
    nombreComercial: 'Floramite 240 SC',
    ingredienteActivo: 'Bifenazato 240 g/L',
    grupo: 'ACARICIDA',
    plaga: 'Arañita bimaculada, arañita roja',
    dosis: '60',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },
  {
    id: 'vertimec-18ec',
    nombreComercial: 'Vertimec 1.8 EC',
    ingredienteActivo: 'Abamectin 18 g/L',
    grupo: 'ACARICIDA',
    plaga: 'Arañita bimaculada (estados móviles)',
    dosis: '75',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '14 días',
  },
  {
    id: 'oberon-240sc',
    nombreComercial: 'Oberon 240 SC',
    ingredienteActivo: 'Spiromesifen 240 g/L',
    grupo: 'ACARICIDA',
    plaga: 'Arañitas (todos los estados)',
    dosis: '50',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '7 días',
  },
  {
    id: 'bifentrina-100ec',
    nombreComercial: 'Bifentrina 100 EC (Talstar)',
    ingredienteActivo: 'Bifentrina 100 g/L',
    grupo: 'ACARICIDA',
    plaga: 'Arañita bimaculada (postcosecha)',
    dosis: '60',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    carencia: '21 días',
  },

  // ── HERBICIDAS ────────────────────────────────────────────────────────────────
  {
    id: 'roundup-controlmax',
    nombreComercial: 'Roundup Controlmax (Faena)',
    ingredienteActivo: 'Glifosato 68% SG / 48% SL',
    grupo: 'HERBICIDA',
    plaga: 'Malezas anuales y perennes (hoja ancha y angosta)',
    dosis: '3',
    unidad: 'kg/ha',
    tipoDosis: 'porHectarea',
    observaciones: 'Uso restringido en entre-hilera. Proteger el tronco del árbol.',
  },
  {
    id: 'alion-500sc',
    nombreComercial: 'Alion 500 SC',
    ingredienteActivo: 'Indaziflam 500 g/L',
    grupo: 'HERBICIDA',
    plaga: 'Malezas anuales (residual pre-emergente)',
    dosis: '0.2',
    unidad: 'L/ha',
    tipoDosis: 'porHectarea',
    observaciones: 'Aplicar después de lluvia >10 mm. Combinar con Glifosato para malezas emergidas.',
  },
  {
    id: 'herbadox-45cs',
    nombreComercial: 'Herbadox 45 CS',
    ingredienteActivo: 'Pendimethalin 45%',
    grupo: 'HERBICIDA',
    plaga: 'Malezas anuales gramíneas y hoja ancha (pre-emergente)',
    dosis: '2.5',
    unidad: 'L/ha',
    tipoDosis: 'porHectarea',
    carencia: '60 días',
    observaciones: 'Incorporar al suelo con lluvia o riego. No aplicar en suelo seco.',
  },
  {
    id: 'fusilade-forte',
    nombreComercial: 'Fusilade Forte',
    ingredienteActivo: 'Fluazifop-p-butil 150 g/L',
    grupo: 'HERBICIDA',
    plaga: 'Malezas gramíneas anuales y perennes',
    dosis: '1.5',
    unidad: 'L/ha',
    tipoDosis: 'porHectarea',
    carencia: '30 días',
  },
  {
    id: 'gramoxone-276sl',
    nombreComercial: 'Gramoxone 276 SL',
    ingredienteActivo: 'Paraquat 276 g/L',
    grupo: 'HERBICIDA',
    plaga: 'Control de contacto de malezas emergidas',
    dosis: '2.5',
    unidad: 'L/ha',
    tipoDosis: 'porHectarea',
    observaciones: 'Uso restringido SAG. Equipo de protección obligatorio.',
  },
  {
    id: 'selector-120ec',
    nombreComercial: 'Selector 120 EC',
    ingredienteActivo: 'Clethodim 120 g/L',
    grupo: 'HERBICIDA',
    plaga: 'Gramíneas anuales y perennes (post-emergente)',
    dosis: '1.5',
    unidad: 'L/ha',
    tipoDosis: 'porHectarea',
    carencia: '45 días',
  },

  // ── FERTILIZANTES FOLIARES ────────────────────────────────────────────────────
  {
    id: 'nutriboro',
    nombreComercial: 'Nutriboro (Basfoliar Boro SL)',
    ingredienteActivo: 'Boro 11% (ácido bórico)',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición: Cuajado, polinización, formación fruto',
    dosis: '67',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'nutri-ca',
    nombreComercial: 'Nutri Ca (Basfoliar Ca SL)',
    ingredienteActivo: 'Calcio 14,8%',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición: Firmeza de frutos, reducir bitter pit',
    dosis: '133',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'cloruro-calcio',
    nombreComercial: 'Cloruro de Calcio 77%',
    ingredienteActivo: 'Cloruro de Calcio 770 g/kg',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición: Firmeza, cracking, bitter pit',
    dosis: '600',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
    observaciones: 'Aplicar solo. Cuidado con fitotoxicidad en calor.',
  },
  {
    id: 'nutri-zn',
    nombreComercial: 'Nutri Zn (Basfoliar Zn Flo)',
    ingredienteActivo: 'Zinc 12%',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición: Crecimiento, activación enzimática',
    dosis: '33',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'nutri-k',
    nombreComercial: 'Nutri K (Sulfato de Potasio)',
    ingredienteActivo: 'Potasio 31%',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición: Color, madurez, calidad de fruta',
    dosis: '300',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'nutri-mg',
    nombreComercial: 'Nutri Mg (Basfoliar Mg Flo)',
    ingredienteActivo: 'Magnesio 6%',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición: Síntesis de clorofila, fotosíntesis',
    dosis: '133',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'basfoliar-36-extra',
    nombreComercial: 'Basfoliar 36 Extra SL',
    ingredienteActivo: 'N 7% + Mg 1% + B 0.02% + Zn 0.02%',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición completa: crecimiento vegetativo y fruto',
    dosis: '250',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'phostin-ca',
    nombreComercial: 'Phostin Ca',
    ingredienteActivo: 'P₂O₅ 31% + CaO 5,6% + N 3,9%',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición: Aumentar color, firmeza pre-cosecha',
    dosis: '666',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'erger',
    nombreComercial: 'Erger',
    ingredienteActivo: 'Nitrógeno amino 50 g/L',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Estimulación de brotación post-Dormex',
    dosis: '5',
    unidad: '% v/v',
    tipoDosis: 'por100L',
    observaciones: 'Aplicar 5 días después del Dormex junto con Nitrato de Calcio.',
  },
  {
    id: 'nitrato-calcio',
    nombreComercial: 'Nitrato de Calcio (15.5-0-0+26.3CaO)',
    ingredienteActivo: 'Nitrato cálcico amoniacal',
    grupo: 'FERTILIZANTE_FOLIAR',
    plaga: 'Nutrición: Firmeza, brotación',
    dosis: '600',
    unidad: 'g/100L',
    tipoDosis: 'por100L',
  },

  // ── BIOESTIMULANTES ───────────────────────────────────────────────────────────
  {
    id: 'kelpak',
    nombreComercial: 'Kelpak (Ecklomar)',
    ingredienteActivo: 'Extracto de Ecklonia maxima',
    grupo: 'BIOESTIMULANTE',
    plaga: 'Mejorar cuaja, calibre, resistencia a estrés',
    dosis: '300',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'stimplex',
    nombreComercial: 'Stimplex (SM6)',
    ingredienteActivo: 'Extracto de Ascophyllum nodosum',
    grupo: 'BIOESTIMULANTE',
    plaga: 'Retención de frutos, calibre, resistencia estrés',
    dosis: '200',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
  },
  {
    id: 'biozyme',
    nombreComercial: 'Biozyme TF',
    ingredienteActivo: 'Extractos vegetales, fitohormonas (AIA, AG, CK)',
    grupo: 'BIOESTIMULANTE',
    plaga: 'Aumento de calibre, cuaja',
    dosis: '1.5',
    unidad: 'L/ha',
    tipoDosis: 'porHectarea',
    observaciones: 'Dosis según potencial productivo del huerto.',
  },
  {
    id: 'progibb-40sg',
    nombreComercial: 'Progibb 40 SG (Biofrut)',
    ingredienteActivo: 'Ácido Giberélico 40%',
    grupo: 'BIOESTIMULANTE',
    plaga: 'Calibre, firmeza, elongación del fruto',
    dosis: '—',
    unidad: 'g/100L según variedad',
    tipoDosis: 'por100L',
    observaciones: 'DOSIS POR VARIEDAD. Revisar instructivo. Usar en estado pajizo y/o 14 días post-plena flor.',
  },
  {
    id: 'dropper',
    nombreComercial: 'Dropper',
    ingredienteActivo: 'Tidiazurón (TDZ)',
    grupo: 'BIOESTIMULANTE',
    plaga: 'Uniformar y aumentar calibre',
    dosis: '15',
    unidad: 'cc/100L',
    tipoDosis: 'por100L',
    observaciones: 'Dos aplicaciones: 7 y 14 días post-plena flor. Última aplicación con menor dosis.',
  },
  {
    id: 'kamasol-humic',
    nombreComercial: 'Kamasol Humic SL',
    ingredienteActivo: 'Ácidos húmicos y fúlvicos',
    grupo: 'BIOESTIMULANTE',
    plaga: 'Materia orgánica, estructura de suelo, absorción nutrientes',
    dosis: '5',
    unidad: 'L/ha por riego',
    tipoDosis: 'riego',
    observaciones: 'Parcializar en 8 aplicaciones de 5 L/ha cada una vía riego.',
  },
  {
    id: 'deltabiotic',
    nombreComercial: 'Deltabiotic',
    ingredienteActivo: 'PGPR (bacterias promotoras de crecimiento)',
    grupo: 'BIOESTIMULANTE',
    plaga: 'Microorganismos benéficos de suelo',
    dosis: '1',
    unidad: 'L/ha por riego',
    tipoDosis: 'riego',
    observaciones: 'Aplicar en un solo riego junto con primera dosis de Kamasol.',
  },
  {
    id: 'pilatus',
    nombreComercial: 'Pilatus',
    ingredienteActivo: 'Extractos de origen vegetal',
    grupo: 'BIOESTIMULANTE',
    plaga: 'Estimulante de crecimiento radical',
    dosis: '3',
    unidad: 'L/ha por riego',
    tipoDosis: 'riego',
    observaciones: 'Aplicar en flush de crecimiento radical (octubre).',
  },

  // ── OTROS ─────────────────────────────────────────────────────────────────────
  {
    id: 'dormex',
    nombreComercial: 'Dormex (Cianamida 500 SL)',
    ingredienteActivo: 'Cianamida Hidrogenada 49%',
    grupo: 'OTRO',
    plaga: 'Ruptura de dormancia, uniformidad de brotación',
    dosis: '—',
    unidad: 'según variedad / L/100L',
    tipoDosis: 'por100L',
    carencia: '—',
    observaciones: 'DOSIS ESTRICTA POR VARIEDAD. Aplicar con T° > 7°C. Aplicar ERGER + CaNO3 5 días después.',
  },
  {
    id: 'diazol',
    nombreComercial: 'Diazol (Diazinon)',
    ingredienteActivo: 'Diazinon 600 g/L',
    grupo: 'OTRO',
    plaga: 'Burrito de los frutales (larvas en suelo)',
    dosis: '5',
    unidad: 'L/ha vía riego',
    tipoDosis: 'riego',
    carencia: '—',
    observaciones: 'Una sola aplicación en postcosecha. Inyectar al inicio del riego.',
  },
]

export function getProductosByGrupo(grupo: GrupoProducto): ProductoSAG[] {
  return PRODUCTOS_SAG.filter((p) => p.grupo === grupo)
}

export function getGrupoInfo(grupo: GrupoProducto) {
  return GRUPOS_PRODUCTO.find((g) => g.value === grupo)
}
